CREATE TABLE `merit_edit_requests` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `fk_apply_id` int(11) NOT NULL,
  `fk_post_id` int(11) NOT NULL,
  `fk_applicant_id` int(11) NOT NULL,
  `district_id` int(11) DEFAULT NULL,
  `project_code` int(11) DEFAULT NULL,
  `requested_by` int(11) NOT NULL,
  `requested_role` varchar(50) DEFAULT NULL,
  `requested_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status` enum('Pending','Approved','Rejected') NOT NULL DEFAULT 'Pending',
  `request_count` int(11) NOT NULL DEFAULT 1,
  `approve_count` int(11) NOT NULL DEFAULT 0,
  `approved_by` int(11) DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `admin_remark` varchar(1000) DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_apply_post` (`fk_apply_id`,`fk_post_id`),
  KEY `idx_apply_post_applicant` (`fk_apply_id`,`fk_post_id`,`fk_applicant_id`),
  KEY `idx_status` (`status`),
  KEY `idx_requested_by` (`requested_by`),
  KEY `idx_approved_by` (`approved_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
